obj-m = mouse.o
MODULE = mouse
DATA = arrow.png brush.png bucket.png cell.png cross.png eraser1.png eraser2.png eraser3.png eyedropper.png fancycross.png finger.png hand.png hourglass.png ibeam.png lasso.png pencil.png spraypaint.png watch.png zoom.png zoomin.png zoomout.png
