MODULE = vortex
DATA = 
obj-m = render.o console.o levels.o vstars.o vgamobjs.o vortex.o

HFILES = console.h levels.h render.h vgamobjs.h vglobals.h vstars.h

console.c: $(HFILES)
levels.c: $(HFILES)
render.c: $(HFILES)
vgamobjs.c: $(HFILES)
vortex.c: $(HFILES)
vstars.c: $(HFILES)
