MODULE = vortex
DATA = 
obj-m = render.o console.o levels.o vgamobjs.o vortex.o \
	starfield.o

HFILES = console.h levels.h render.h vgamobjs.h vglobals.h

console.c: $(HFILES)
levels.c: $(HFILES)
render.c: $(HFILES)
vgamobjs.c: $(HFILES)
vortex.c: $(HFILES)
