#
# Makefile for iPod
#

# Object file lists.

obj-y += arch.o cop.o dma.o hardware.o irq.o

obj-$(CONFIG_AUDIO_IPOD)	+= audio.o
obj-$(CONFIG_IEEE1394_IPOD)	+= tsb43aa82.o
obj-$(CONFIG_KB_IPOD)		+= keyboard.o
obj-$(CONFIG_REMOTE_IPOD)	+= ipodremote.o

