obj-m := legacies.o invaders/invaders.o ipobble/ipobble.o \
         lights/lights.o mandelpod/mandelpod.o matrix/matrix.o \
         minesweeper/minesweeper.o pong/pong.o tictactoe/tictactoe.o \
         tunnel/tunnel.o wumpus/wumpus.o steroids/asteroid.o \
         steroids/main.o steroids/object.o steroids/polygon.o \
         steroids/ship.o steroids/shot.o steroids/vector.o \
         bluecube/box.o bluecube/main.o bluecube/pieces.o
MODULE = legacies
