######################################################################
# Automatically generated by qmake (2.00a) Fri Jan 6 07:53:19 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES = installer.qrc

# Input
HEADERS += installer.h complexwizard.h
SOURCES += installer.cc main.cc complexwizard.cc
